
server:
  port: 8081

spring:
  application:
    name: provider-003
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/1908?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: 123

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8090/eureka
